### ISSUE TITLE
gyp ERR! stack Error: make failed with exit code: 2

### ISSUE THREAD

**Issue by 1166544** [wildfirechat/pc-chat#11]
> ref@1.3.5 install /Volumes/F/WorksArchitecture/pc-chat-master/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
clang: error: no such file or directory: ‘DD/.node-gyp/10.16.3/include/node'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/src'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/deps/openssl/config'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/deps/openssl/openssl/include'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/deps/uv/include'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/deps/zlib'
clang: error: no such file or directory: 'DD/.node-gyp/10.16.3/deps/v8/include'
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/F/WorksArchitecture/pc-chat-master/node_modules/ref
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by imndx** [comment]
你好，pc版本编译，依赖特定的环境。我的node是v10.16.0版本，你可以试下。
