### ISSUE TITLE
转发的消息，撤回时，errorCode返回253

### ISSUE THREAD

**Issue by brian80s** [wildfirechat/pc-chat#19]

**Comment by heavyrain2012** [comment]
253是没有权限，撤回时说明被撤回消息不是本人发送的。当一条消息被转发时，转发成功后消息ID应该更新，撤回更新后的消息id，这个问题我们会处理

**Comment by heavyrain2012** [comment]
我在我们demo上测试没有发现问题啊，是不是你们代码没有更新到最新，或者是自己修改了什么地方？请用我们最新代码测试
