### ISSUE TITLE
windows 运行 npm run dev 报错

### ISSUE THREAD

**Issue by weizihua** [wildfirechat/pc-chat#20]
环境: 
window10
node10.17.0
cmder
vscode

1. 执行了npm run copy-win 之后再执行npm run dev 报 marswrapper.node is not a valid Win32 application.

2 手动下载各种不同版本  marswrapper.win32.node 进行运行 还是报错
![image](https://user-images.githubusercontent.com/7597986/70162735-1c8ea680-16f9-11ea-8bdc-8cf775b60fc8.png)

期望：能正常运行 npm run dev

**Comment by imndx** [comment]
你好，目前windows下只能npm run build打包。
npm run dev的问题，我们在处理中。

**Comment by heavyrain2012** [comment]
請用最新版本驗證
