### ISSUE TITLE
Windows版打包安装打开时报错。

### ISSUE THREAD

**Issue by KookCaptain** [wildfirechat/pc-chat#23]
A JavaScript error occurred in the main process Uncaught Exception:Error: Cannot open /opt/wildfirechat/resources/app.asar/marswrapper.node: Error: libdouble-conversion.so.1: cannot open shared object file: No such file or directory。

**Comment by imndx** [comment]
你好，你是在linux下打包吗？

需要这个依赖：```libdouble-conversion.so.1```，可以手动安装一下

请参考：[Ubuntu](https://howtoinstall.co/en/ubuntu/trusty/libdouble-conversion-dev)，其他发行版的话，可以google一下

**Comment by KookCaptain** [comment]
> 你好，你是在linux下打包吗？
> 
> 需要这个依赖：`libdouble-conversion.so.1`，可以手动安装一下
> 
> 请参考：[Ubuntu](https://howtoinstall.co/en/ubuntu/trusty/libdouble-conversion-dev)，其他发行版的话，可以google一下

你好，我是在windows下打包的，找到原因了，是win-qt-denpendency路径下没有Qt5Core.dll导致的。感谢解答！

**Comment by imndx** [comment]
你好，是因为没执行：```npm run copy-win```或者```npm run copy-win32```吗？

**Comment by KookCaptain** [comment]
> 你好，是因为没执行：`npm run copy-win`或者`npm run copy-win32`吗？

执行过，可能是早些时候研究项目时误删了一些文件造成的，应该是我自己造成的。
