### ISSUE TITLE
无法直接创建会话

### ISSUE THREAD

**Issue by jacker18** [wildfirechat/pc-chat#24]
必须要发送一条消息会话才会真正生成，而不是点击发送消息就会生成会话;

**Comment by heavyrain2012** [comment]
提供了新接口，updateCoversationTimestamp，可以在进入会话时判断如果当前会话不存在消息，就调用这个接口产生一个新的会话，需要更新SDK

**Comment by imndx** [comment]
请参考```wfc.setConversationTimestamp```
