### ISSUE TITLE
修改个人信息函数没有实现

### ISSUE THREAD

**Issue by Bluetorch2016** [wildfirechat/pc-chat#25]
pc-chat/src/js/wfc/client/wfc.js的modifyMyInfo函数调用pc-chat/src/js/wfc/proto/proto.min.js的modifyMyInfo函数，但是pc-chat/src/js/wfc/proto/proto.min.js的modifyMyInfo是空函数，没有具体的实现

**Comment by heavyrain2012** [comment]
已修改，需要更新协议栈
