### ISSUE TITLE
win7  x64   表情显示不了

### ISSUE THREAD

**Issue by longzitianya** [wildfirechat/pc-chat#26]
![2020-06-14_081223](https://user-images.githubusercontent.com/4787506/84581726-f881ef80-ae16-11ea-84ba-fa4fc81f8058.jpg)
![2020-06-14_081303](https://user-images.githubusercontent.com/4787506/84581727-fc157680-ae16-11ea-8a29-5db3eb67e51d.jpg)

**Comment by imndx** [comment]
所有表情，还是部分？

**Comment by imndx** [comment]
已修复，请用最新代码测试
