### ISSUE TITLE
表情分类切换BUG

### ISSUE THREAD

**Issue by pullwindyuan** [wildfirechat/pc-chat#27]
0.3.4版本，并且代码使用了最新代码：
当我们在选择切换不容种类的表情的时候会出现表情栏自动关闭的问题：
1、点击输入框上方的红心；
2、点击选择切换到任意一栏表情；
3、再选择其他任意表情栏切换；
4、此时表情栏以外关闭；
5、此问题必现。

同时还存在除了第一类常规表情外，后面的所有分类的表情均无法输入和显示

**Comment by imndx** [comment]
> 同时还存在除了第一类常规表情外，后面的所有分类的表情均无法输入和显示

这个问题，可以用最新代码测试，应当已经修复。
