### ISSUE TITLE
PC会话转接功能

### ISSUE THREAD

**Issue by zzwooc** [wildfirechat/pc-chat#29]
【A】要把【A】和【甲】的对话转接给【B】，并且【A】和【甲】的历史消息，【B】也能看到，且【B】和【甲】都能收到相应的通知。转接给谁，这个谁可以筛选

**Comment by heavyrain2012** [comment]
请参考文档 https://docs.wildfirechat.cn/blogs/野火IM应用之如何做一套简单客服系统.html
