### ISSUE TITLE
PC端更换APP_SERVER = 'http://wildfirechat.cn:8888地址，无法扫描登录

### ISSUE THREAD

**Issue by likuiliang** [wildfirechat/pc-chat#30]
PC端版本，在config.js文件中使用http://wildfirechat.cn:8888地址，能使用移动端App进行扫码登录，但是修改为自己部署的地址后，就出现扫描成功，但是PC的页面不跳转，还是在二维码页面。请问这是什么原因，是还有其它配置需要修改吗？

    static DEFAULT_PORTRAIT_URL = 'https://static.wildfirechat.cn/user-fallback.png';
    static APP_SERVER = 'http://wildfirechat.cn:8888';
    static QR_CODE_PREFIX_PC_SESSION = "wildfirechat://pcsession/";
    static ICE_ADDRESS = 'turn:turn.wildfirechat.cn:3478';

**Comment by imndx** [comment]
你好，PC SDK 是需要购买授权，才能使用的。可以参考这儿：[野火IM](https://docs.wildfirechat.cn/)

**Comment by likuiliang** [comment]
（1）专业版IM服务就是C++的跨平台服务吗？是不是移动App使用的是一套跨平台服务，我们购买后，所有平台通用？购买授权后，你们重新给我们重新打所有的平台的跨平台服务SDK吗？
 （2）你们文档上说的 PC SDK（Electron版本）是什么？是相当于UI吗？我看GitHub上也是开源的，你们这个收费和免费的有什么区别？

**Comment by imndx** [comment]
1. 专业版IM Server是和[社区版IM Server](https://github.com/wildfirechat/server)对应的一个版本，性能更好，功能更强大。

2. PC SDK(Electron版本) 就是[pc-chat](https://github.com/wildfirechat/pc-chat) 所使用的一个库文件，[pc-chat](https://github.com/wildfirechat/pc-chat) 包含了上层开源的UI部分和底层闭源的SDK库。

**Comment by likuiliang** [comment]
感谢你的及时解答。
