### ISSUE TITLE
没有音频/视频录入设备无法发起群语音/视频

### ISSUE THREAD

**Issue by Bluetorch2016** [wildfirechat/pc-chat#32]
当我禁用本机麦克风或者摄像头之后，无法发起群音频/视频

**Comment by imndx** [comment]
你好，目前设计如此。

如果需要没有音视频设备也能发起音视频通话，可修改：```avenginekitproxy.js```里面的```startCall```和```onReceiveMessage```的前置逻辑，将本机是否能正常支持音视频通话的逻辑移除。
