### ISSUE TITLE
安装依赖报错-- node-gyp rebuild 报错   windows 环境  node版本 10.16.0  python版本 2.7.15 npm版本 6.9.0

### ISSUE THREAD

**Issue by yufengtan** [wildfirechat/pc-chat#33]
D:\workspace\pc-chat\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  module_init.cc
  sleep_cpp11.cc
  sleep_posix.cc
  sleep_win.cc
  win_delay_load_hook.cc
C:\Users\Administrator\.node-gyp\10.16.0\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x312F8A [D:\workspace\pc-chat\node_modules\sleep\build\node_sleep.vcxproj]
gyp ERR! build error 
--------------------------------------------------------------------------------------------------------
gyp: binding.gyp not found (cwd: D:\workspace\pc-chat) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.0\node_modules\node-gyp\lib\configure.js:350:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\workspace\pc-chat
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok

**Comment by imndx** [comment]
> npm install --global --vs2015 windows-build-tools # 安装内容较多，如果网络情况不好可能需要等较长时间，选择早上网络较好时安装是个好的选择

请问下，这一步是否执行成功？

**Comment by yufengtan** [comment]
问题已解决 升了node版本 为14.2.0

发自我的iPhone

**Comment by imndx** [comment]
你好，可以分享下具体的解决过程吗 ？
