### ISSUE TITLE
打包后windows安装之后运行出错

### ISSUE THREAD

**Issue by zzwooc** [wildfirechat/pc-chat#34]
如下图，是打包win之后安装了，然后运行出错，但是打包出来的mac的安装之后，运行就没问题。

![image](https://user-images.githubusercontent.com/19815528/88874288-4b8df580-d251-11ea-9750-aa5d78f23db9.png)

**Comment by imndx** [comment]
> win平台野火客户端依赖Visual C++ Redistributable Package runtime。如果用户PC上没有安装就需要安装之后才能运行，请从微软官方下载安装 https://www.microsoft.com/zh-CN/download/details.aspx?id=48145。

你好，这个有安装吗？

另外，请提供下系统信息

**Comment by zzwooc** [comment]
> > win平台野火客户端依赖Visual C++ Redistributable Package runtime。如果用户PC上没有安装就需要安装之后才能运行，请从微软官方下载安装 [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)
> 
> 你好，这个有安装吗？
> 
> 另外，请提供下系统信息

有安装，package-win32 打包出来可以，package-win 打包出来的安装后是上面的错误

**Comment by imndx** [comment]
> > > win平台野火客户端依赖Visual C++ Redistributable Package runtime。如果用户PC上没有安装就需要安装之后才能运行，请从微软官方下载安装 [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)
> > 
> > 
> > 你好，这个有安装吗？
> > 另外，请提供下系统信息
> 
> 有安装，package-win32 打包出来可以，package-win 打包出来的安装后是上面的错误

上面的依赖有32位和64位之分，安装64位版本时，```npm run package-win```打出来的包正常吗？

**Comment by zzwooc** [comment]
> > > > win平台野火客户端依赖Visual C++ Redistributable Package runtime。如果用户PC上没有安装就需要安装之后才能运行，请从微软官方下载安装 [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)
> > > 
> > > 
> > > 你好，这个有安装吗？
> > > 另外，请提供下系统信息
> > 
> > 
> > 有安装，package-win32 打包出来可以，package-win 打包出来的安装后是上面的错误
> 
> 上面的依赖有32位和64位之分，安装64位版本时，`npm run package-win`打出来的包正常吗？

就是64位的不正常，32位的正常

**Comment by heavyrain2012** [comment]
Visual C++ Redistributable for Visual Studio 2015 下载时，有64位和32位程序包，请问安装64位程序包了吗

**Comment by lilong7676** [comment]
@sundaywill 请问最后怎么解决的？
