### ISSUE TITLE
windows系统  修改当前用户信息时报错!

### ISSUE THREAD

**Issue by songuu** [wildfirechat/pc-chat#36]
Uncaught Error: Could not call remote method 'modifyMyInfo'. Check that the method signature is correct. Underlying error: Wrong arguments, should be (int, string, func, func)
Underlying stack: TypeError: Wrong arguments, should be (int, string, func, func)

// 但是我看proto.min.js 里面是实现了的。
modifyMyInfo(type, value, successCB, failCB) {
        proto.modifyMyInfo(type, value, () => {
            if (successCB) {
                successCB();
            }
        }, (errorCode) => {
            if (failCB) {
                failCB(errorCode);
            }
        });
    }

**Comment by imndx** [comment]
你好，可能是你的参数类型错了。

```
 /**
     * 修改个人信息，一次只能修改一个信息
     * @param {number} type 修改类型，可选类型参考{@link ModifyMyInfoType}
     * @param {string} value 修改值
     * @param  {function ()} successCB
     * @param {function (errorCode)} failCB
     */
    modifyMyInfo(type, value, successCB, failCB) {
        impl.modifyMyInfo(type, value, successCB, failCB);
    }
```
