### ISSUE TITLE
发送sql语句有问题

### ISSUE THREAD

**Issue by littlewang** [wildfirechat/pc-chat#37]
发送sql语句时 文本无法被选中 没法把文本复制出来，在app端查看内容 把html的标签也显示出来了

**Comment by imndx** [comment]
sql语句是从网页上复制过来，然后粘贴进去的吗？

**Comment by littlewang** [comment]
没错是从网页复制过去的，手动输入和从工具复制过去没问题，但是使用钉钉发送网页复制过来的sql语句 在手机端看是正常的。
