### ISSUE TITLE
从网页复制的内容发送的时候没有去掉样式

### ISSUE THREAD

**Issue by littlewang** [wildfirechat/pc-chat#39]
网页复制的内容没有去掉样式导致 手机端查看 一堆乱码，同样的操做在 微信电脑端 钉钉电脑端都是复制到输入框里 自动把央视标签去掉了的，从网页复制内容到电脑端输入框的情况还是非常多的，希望解决这个问题， 不然要先复制到记事本 再复制到聊天框 非常的麻烦。

**Comment by imndx** [comment]
已经解决，请更新最新代码测试。
