### ISSUE TITLE
wfc.disconnect有问题

### ISSUE THREAD

**Issue by linanzhi** [wildfirechat/pc-chat#40]
用第一个账户登录成功后，调用wfc.disconnect断开连接后，用第二个账户登录然后 连IM server的时候，用的username是上一个用户的，导致连接失败

**Comment by linanzhi** [comment]
![image](https://user-images.githubusercontent.com/39115668/91707681-c2047700-ebb2-11ea-81f3-e53f906239f7.png)

**Comment by imndx** [comment]
已解决，请更新到最新测试
