### ISSUE TITLE
版本自动升级功能无效，直接报错

### ISSUE THREAD

**Issue by tianyazjq** [wildfirechat/pc-chat#43]
## 提issue小提示
版本自动升级功能无效，直接报错

### 操作说明
托盘右键点击升级

### 表现现象

![image](https://user-images.githubusercontent.com/5754329/96330562-ada80b00-1088-11eb-976e-fa886653ed4e.png)

**Comment by imndx** [comment]
你好，我们目前尚未开发自动升级功能。

**Comment by heavyrain2012** [comment]
自动升级功能需要客户自己来开发，开发教程 https://www.electronjs.org/docs/tutorial/updates
