### ISSUE TITLE
小白求问，这个project是依赖于野火的IM SDK吗？为什么用野火IM移动端扫码才可登录

### ISSUE THREAD

**Issue by Flyooofly** [wildfirechat/pc-chat#44]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

### 日志
请附上相关的错误

### 预期结果
你认为正确的表现应该是什么样的。

### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现？PC SDK版本信息？

### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
你好
是的，依赖于野火IM SDK。默认连接的APP Server 和IM Server都是野火官方服务，所以需要野火IM 移动端扫码才能登录。

**Comment by Flyooofly** [comment]
好的谢谢
